version: '3.1'

services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 0.0.0.0:2368:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ghost
      url: https://${DOMAIN}
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 0.0.0.0:3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  nginx:
    image: nginx:alpine
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./ssl:/etc/ssl